# Generated by Django 6.0.4 on 2026-04-21 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pendiente"),
                    ("in_progress", "En progreso"),
                    ("blocked", "Bloqueado"),
                    ("cancelled", "Cancelado"),
                    ("completed", "Completado"),
                ],
                default="pending",
                max_length=20,
                verbose_name="estado",
            ),
        ),
    ]
