# Generated by Django 6.0.4 on 2026-04-13 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="step",
            name="title",
            field=models.CharField(
                blank=True, default="", max_length=200, verbose_name="título"
            ),
        ),
    ]
