# Generated by Django 6.0.4 on 2026-04-20 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0004_material_available"),
    ]

    operations = [
        migrations.AddField(
            model_name="tool",
            name="available",
            field=models.BooleanField(default=False, verbose_name="disponible"),
        ),
    ]
