# Generated by Django 6.0.4 on 2026-04-20 20:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0005_tool_available"),
    ]

    operations = [
        migrations.CreateModel(
            name="TaskLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.URLField(max_length=500, verbose_name="URL")),
                (
                    "description",
                    models.CharField(max_length=200, verbose_name="descripción"),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="links",
                        to="tasks.task",
                    ),
                ),
            ],
            options={
                "verbose_name": "enlace",
                "verbose_name_plural": "enlaces",
                "ordering": ["pk"],
            },
        ),
    ]
