# Generated by Django 6.0.4 on 2026-04-21 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0006_tasklink"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pendiente"),
                    ("in_progress", "En progreso"),
                    ("blocked", "Bloqueada"),
                    ("cancelled", "Cancelada"),
                    ("completed", "Completada"),
                ],
                default="pending",
                max_length=20,
                verbose_name="estado",
            ),
        ),
    ]
