# Generated by Django 6.0.4 on 2026-04-21 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0007_task_status_completed"),
    ]

    operations = [
        migrations.CreateModel(
            name="AIChat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("prompt", models.TextField(verbose_name="pregunta")),
                ("response", models.TextField(verbose_name="respuesta")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_chats",
                        to="tasks.task",
                    ),
                ),
            ],
            options={
                "verbose_name": "chat IA",
                "verbose_name_plural": "chats IA",
                "ordering": ["created_at"],
                "indexes": [
                    models.Index(
                        fields=["task", "created_at"],
                        name="tasks_aicha_task_id_856cba_idx",
                    )
                ],
            },
        ),
    ]
