# Generated by Django 6.0.4 on 2026-04-25 17:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("projects", "0002_project_status"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Design",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="título")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="descripción"),
                ),
                (
                    "original_image",
                    models.CharField(
                        max_length=500, verbose_name="imagen original (ruta)"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="designs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="creado por",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="designs",
                        to="projects.project",
                        verbose_name="proyecto",
                    ),
                ),
            ],
            options={
                "verbose_name": "idea de diseño",
                "verbose_name_plural": "ideas de diseño",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DesignImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("prompt", models.TextField(verbose_name="prompt")),
                (
                    "generated_image",
                    models.CharField(
                        blank=True,
                        max_length=500,
                        verbose_name="imagen generada (ruta)",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendiente"),
                            ("completed", "Completado"),
                            ("failed", "Fallido"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="estado",
                    ),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, verbose_name="mensaje de error"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="design_images",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="creado por",
                    ),
                ),
                (
                    "design",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="designs.design",
                        verbose_name="idea",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="refinements",
                        to="designs.designimage",
                        verbose_name="imagen base",
                    ),
                ),
            ],
            options={
                "verbose_name": "imagen generada",
                "verbose_name_plural": "imágenes generadas",
                "ordering": ["-created_at"],
            },
        ),
    ]
